# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  skip: [pylint]
  autofix_prs: true
  autofix_commit_msg: "fix: [pre-commit.ci] auto fixes [...]"
  autoupdate_commit_msg: "chore(pre-commit): [pre-commit.ci] autoupdate"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: debug-statements
      - id: double-quote-string-fixer
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
        stages: [commit, push, manual]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [commit, push, manual]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black-jupyter
        stages: [commit, push, manual]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py37-plus] # sync with requires-python
        stages: [commit, push, manual]
        exclude: |
          (?x)(
            ^examples/
          )
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-docstrings
          - flake8-pyi
          - flake8-simplify
        exclude: |
          (?x)(
            ^examples/|
            ^tests/|
            ^docs/source/conf.py$
          )
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
        stages: [commit, push, manual]
        exclude: |
          (?x)(
            ^docs/|
            ^examples/|
            ^tests/|
            ^setup.py$
          )
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: [".[toml]"]
        exclude: |
          (?x)(
            ^.github/|
            ^docs/|
            ^examples/|
            ^tests/|
            ^setup.py$
          )
