# Copyright 2022 MetaOPT Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
#
# Create virtual environment with command:
#
#   $ CONDA_OVERRIDE_CUDA=11.7 conda env create --file conda-recipe.yaml
#

name: torchopt

channels:
  - pytorch
  - defaults
  - nvidia
  - conda-forge

dependencies:
  - python = 3.8
  - pip

  # Learning
  - pytorch::pytorch >= 1.13  # sync with project.dependencies
  - pytorch::torchvision
  - pytorch::pytorch-mutex = *=*cuda*
  - pip:
      - torchviz
      - sphinxcontrib-katex  # for documentation
  - jax                      # for tutorials
  - jaxlib >= 0.3=*cuda*     # for tutorials
  - optax                    # for tutorials
  - tensorboard              # for examples
  - wandb

  # Device select
  - pytorch::pytorch-cuda = 11.7
  - cudnn

  # Build toolchain
  - cmake >= 3.4
  - make
  - cxx-compiler
  - gxx = 10
  - nvidia::cuda-nvcc
  - nvidia::cuda-cudart-dev
  - patchelf >= 0.9
  - pybind11

  # Misc
  - typing-extensions >= 4.0.0
  - numpy
  - matplotlib-base
  - seaborn
  - python-graphviz
  - pillow
  - setproctitle

  # Documentation
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autobuild
  - sphinx-copybutton
  - sphinxcontrib-spelling
  - sphinxcontrib-bibtex
  - sphinx-autodoc-typehints
  - pyenchant
  - myst-nb
  - ipykernel
  - pandoc
  - docutils

  # Testing
  - pytest
  - pytest-cov
  - pytest-xdist
  - isort
  - conda-forge::black-jupyter >= 22.6.0
  - pylint
  - mypy
  - flake8
  - flake8-bugbear
  - doc8 < 1.0.0a0
  - pydocstyle
  - clang-format >= 14
  - clang-tools  # clang-tidy
  - cpplint
  - pre-commit
