# Copyright 2022-2023 MetaOPT Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
#
# Create virtual environment with command:
#
#   $ CONDA_OVERRIDE_CUDA=11.7 conda env create --file docs/conda-recipe.yaml
#

name: torchopt-docs

channels:
  - pytorch
  - nvidia/label/cuda-11.7.1
  - defaults
  - conda-forge

dependencies:
  - python = 3.10
  - pip

  # Learning
  - pytorch::pytorch >= 1.13  # sync with project.dependencies
  - pytorch::cpuonly
  - pytorch::pytorch-mutex = *=*cpu*
  - pip:
      - torchviz
      - sphinxcontrib-katex  # for documentation

  # Build toolchain
  - cmake >= 3.11
  - make
  - cxx-compiler
  - nvidia/label/cuda-11.7.1::cuda-nvcc
  - nvidia/label/cuda-11.7.1::cuda-cudart-dev
  - pybind11 >= 2.10.1

  # Misc
  - optree >= 0.4.1
  - typing-extensions >= 4.0.0
  - numpy
  - matplotlib-base
  - seaborn
  - python-graphviz
  - pillow

  # Documentation
  - sphinx >= 5.2.1
  - sphinx-rtd-theme
  - sphinx-autobuild
  - sphinx-copybutton
  - sphinxcontrib-spelling
  - sphinxcontrib-bibtex
  - sphinx-autodoc-typehints >= 1.19.2
  - pyenchant
  - hunspell-en
  - myst-nb
  - ipykernel
  - docutils
