name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous run
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python 3.7  # the lowest version we support
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
          update-environment: true

      - name: Setup CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.7
        id: cuda-toolkit
        with:
          cuda: "11.3.1"
          method: network
          sub-packages: '["nvcc"]'
      - run: |
          echo "Installed CUDA version is: ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "CUDA install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install dependencies
        run: |
          python -m pip install -r tests/requirements.txt

      - name: Install TorchOpt
        run: |
          python -m pip install -e .

      - name: flake8
        run: |
          make flake8

      - name: isort and yapf
        run: |
          make py-format

      - name: addlicense
        run: |
          make addlicense

      - name: mypy
        run: |
          make mypy

    # - name: docstyle
    #   run: |
    #     make docstyle

    # - name: spelling
    #   run: |
    #     make spelling
