name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - setup.py
      - setup.cfg
      - pyproject.toml
      - MANIFEST.in
      - CMakeLists.txt
      - include/**
      - src/**
      - tests/**
      - torchopt/**
      - .github/workflows/tests.yml
  # Allow to trigger the workflow manually
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7" # the lowest version we support (sync with requires-python in pyproject.toml)
          update-environment: true

      - name: Setup CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: "11.7.0"
          method: network
          sub-packages: '["nvcc"]'
      - run: |
          CUDA_VERSION="${{steps.cuda-toolkit.outputs.cuda}}"
          echo "CUDA_VERSION=${CUDA_VERSION}" >> "${GITHUB_ENV}"
          PIP_EXTRA_INDEX_URL="https://download.pytorch.org/whl/cu$(echo "${CUDA_VERSION}" | cut -d'.' -f-2  | tr -d '.')"
          echo "PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}" >> "${GITHUB_ENV}"

          echo "Installed CUDA version is: ${CUDA_VERSION}"
          echo "CUDA install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V
          echo "Torch index URL: ${PIP_EXTRA_INDEX_URL}"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          python -m pip install -r tests/requirements.txt

      - name: Install TorchOpt
        env:
          USE_FP16: "ON"
          TORCH_CUDA_ARCH_LIST: "Common"
        run: |
          python -m pip install -vvv -e .

      - name: Test with pytest
        run: |
          make pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./tests/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  test-pure-python:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7" # the lowest version we support (sync with requires-python in pyproject.toml)
          update-environment: true

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: |
          python -m pip install -r tests/requirements.txt

      - name: Install TorchOpt
        run: |
          python -m pip install -vvv -e .
        env:
          TORCHOPT_NO_EXTENSIONS: "true"

      - name: Test with pytest
        run: |
          make pytest
